In [11]:
import pandas as pd
import numpy as np

In [2]:
linelist = pd.read_csv("final.linelist")

In [3]:
linelist

     Unnamed: 0  Line    lambda  Ex.P
0             0   FeI  3440.610  0.00
1             1   FeI  3440.990  0.05
2             2   FeI  3447.280  2.20
3             3   FeI  3450.330  2.22
4             4   FeI  3451.910  2.22
5             5   FeI  3476.700  0.12
6             6   FeI  3490.570  0.05
7             7   FeI  3497.840  0.11
8             8   FeI  3540.120  2.87
9             9   FeI  3565.380  0.96
10           10   FeI  3608.860  1.01
11           11   FeI  3618.770  0.99
12           12   FeI  3647.840  0.92
13           13   FeI  3689.460  2.94
14           14   FeI  3719.930  0.00
15           15   FeI  3727.620  0.96
16           16   FeI  3742.620  2.94
17           17   FeI  3758.230  0.96
18           18   FeI  3763.790  0.99
19           19   FeI  3765.540  3.24
20           20   FeI  3786.680  1.01
21           21   FeI  3787.880  1.01
22           22   FeI  3805.340  3.30
23           23   FeI  3808.730  2.56
24           24   FeI  3815.840  1.48
25           25   FeI  3820.430  0.86
26           26   FeI  3825.880  0.91
27           27   FeI  3827.820  1.56
28           28   FeI  3840.440  0.99
29           29   FeI  3841.050  1.61
..          ...   ...       ...   ...
502         502  FeII  4491.400  2.86
503         503  FeII  4508.280  2.86
504         504  FeII  4515.340  2.84
505         505  FeII  4522.630  2.84
506         506  FeII  4549.470  2.83
507         507  FeII  4555.890  2.83
508         508  FeII  4576.332  2.84
509         509  FeII  4583.830  2.81
510         510  FeII  4620.510  2.83
511         511  FeII  4923.930  2.89
512         512  FeII  4993.350  2.81
513         513  FeII  5197.566  3.23
514         514  FeII  5234.630  3.22
515         515  FeII  5256.930  2.89
516         516  FeII  5264.801  3.23
517         517  FeII  5275.996  3.20
518         518  FeII  5316.607  3.15
519         519  FeII  5316.780  3.22
520         520  FeII  5325.550  3.22
521         521  FeII  5414.070  3.22
522         522  FeII  5425.250  3.20
523         523  FeII  5534.840  3.25
524         524  FeII  5991.370  3.15
525         525  FeII  6084.100  3.20
526         526  FeII  6113.320  3.22
527         527  FeII  6149.240  3.89
528         528  FeII  6247.560  3.89
529         529  FeII  6369.460  2.89
530         530  FeII  6432.680  2.89
531         531  FeII  6456.380  3.90

[532 rows x 4 columns]

In [8]:
newlinelist = linelist[~linelist.duplicated(subset=['Line','lambda', "Ex.P"])]

In [12]:
idx_fei = np.where(newlinelist.Line=="FeI")
newlinelist_fei = newlinelist.iloc[idx_fei].sort_values(by=["lambda"])

In [14]:
idx_feii = np.where(newlinelist.Line=="FeII")
newlinelist_feii = newlinelist.iloc[idx_feii].sort_values(by=["lambda"])

In [15]:
newlinelist_feii

     Unnamed: 0  Line    lambda  Ex.P
496         496  FeII  4173.450  2.58
497         497  FeII  4178.860  2.58
498         498  FeII  4233.160  2.58
499         499  FeII  4303.170  2.70
500         500  FeII  4385.380  2.78
501         501  FeII  4416.820  2.78
502         502  FeII  4491.400  2.86
503         503  FeII  4508.280  2.86
504         504  FeII  4515.340  2.84
505         505  FeII  4522.630  2.84
506         506  FeII  4549.470  2.83
507         507  FeII  4555.890  2.83
508         508  FeII  4576.332  2.84
509         509  FeII  4583.830  2.81
510         510  FeII  4620.510  2.83
511         511  FeII  4923.930  2.89
512         512  FeII  4993.350  2.81
513         513  FeII  5197.566  3.23
514         514  FeII  5234.630  3.22
515         515  FeII  5256.930  2.89
516         516  FeII  5264.801  3.23
517         517  FeII  5275.996  3.20
518         518  FeII  5316.607  3.15
519         519  FeII  5316.780  3.22
520         520  FeII  5325.550  3.22
521         521  FeII  5414.070  3.22
522         522  FeII  5425.250  3.20
523         523  FeII  5534.840  3.25
524         524  FeII  5991.370  3.15
525         525  FeII  6084.100  3.20
526         526  FeII  6113.320  3.22
527         527  FeII  6149.240  3.89
528         528  FeII  6247.560  3.89
529         529  FeII  6369.460  2.89
530         530  FeII  6432.680  2.89
531         531  FeII  6456.380  3.90

In [18]:
finalnewlinelist = newlinelist_fei.append(newlinelist_feii, ignore_index=True)
finalnewlinelist = finalnewlinelist[["Line", "lambda", "Ex.P"]]

In [19]:
finalnewlinelist

     Line    lambda  Ex.P
0     FeI  3440.610  0.00
1     FeI  3440.990  0.05
2     FeI  3447.280  2.20
3     FeI  3450.330  2.22
4     FeI  3451.910  2.22
5     FeI  3476.700  0.12
6     FeI  3490.570  0.05
7     FeI  3497.840  0.11
8     FeI  3540.120  2.87
9     FeI  3565.380  0.96
10    FeI  3608.860  1.01
11    FeI  3618.770  0.99
12    FeI  3647.840  0.92
13    FeI  3689.460  2.94
14    FeI  3719.930  0.00
15    FeI  3727.620  0.96
16    FeI  3742.620  2.94
17    FeI  3758.230  0.96
18    FeI  3763.790  0.99
19    FeI  3765.540  3.24
20    FeI  3786.680  1.01
21    FeI  3787.880  1.01
22    FeI  3805.340  3.30
23    FeI  3808.730  2.56
24    FeI  3815.840  1.48
25    FeI  3820.430  0.86
26    FeI  3825.880  0.91
27    FeI  3827.820  1.56
28    FeI  3840.440  0.99
29    FeI  3841.050  1.61
..    ...       ...   ...
432  FeII  4491.400  2.86
433  FeII  4508.280  2.86
434  FeII  4515.340  2.84
435  FeII  4522.630  2.84
436  FeII  4549.470  2.83
437  FeII  4555.890  2.83
438  FeII  4576.332  2.84
439  FeII  4583.830  2.81
440  FeII  4620.510  2.83
441  FeII  4923.930  2.89
442  FeII  4993.350  2.81
443  FeII  5197.566  3.23
444  FeII  5234.630  3.22
445  FeII  5256.930  2.89
446  FeII  5264.801  3.23
447  FeII  5275.996  3.20
448  FeII  5316.607  3.15
449  FeII  5316.780  3.22
450  FeII  5325.550  3.22
451  FeII  5414.070  3.22
452  FeII  5425.250  3.20
453  FeII  5534.840  3.25
454  FeII  5991.370  3.15
455  FeII  6084.100  3.20
456  FeII  6113.320  3.22
457  FeII  6149.240  3.89
458  FeII  6247.560  3.89
459  FeII  6369.460  2.89
460  FeII  6432.680  2.89
461  FeII  6456.380  3.90

[462 rows x 3 columns]

In [21]:
finalnewlinelist.to_csv("newfinal.linelist", index=False)